# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170203_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='first_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(help_text='eg: 123@esp.ext', max_length=128),
        ),
    ]
