# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_join_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(help_text='eg: 123@esp.ext', max_length=128, unique=True),
        ),
    ]
