# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170208_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='default', max_length=128),
        ),
        migrations.AlterField(
            model_name='join',
            name='ip_address',
            field=models.GenericIPAddressField(default='default'),
        ),
    ]
