# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170208_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
